### ISSUE TITLE
Now playing and weather

### ISSUE THREAD

**Issue by zedxot** [addy-dclxvi/Tint2-Theme-Collections#3]
Hello, I'm completely new with tint2 and Openbox. I'm running Openbox on Arch. Everything is working great. But I can't make the now playing and weather work. I'm using your Repentance theme. In another issue, you said I need an API from and paste it to the weather script, but I was unable to find where is that script located. 
And how can I get the now-playing executor work?
Thanks in advanced.

**Comment by addy-dclxvi** [comment]
https://github.com/addy-dclxvi/almighty-dotfiles/tree/master/.executor

The now playing executor is for mpd

**Comment by zedxot** [comment]
Thanks, it's working now. :+1:
